
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/example?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#spring.datasource.username=user
#spring.datasource.password=UserPassword

spring:
  datasource:
#    url:jdbc:h2:file:C:/study-spring/board/h2data:
#    h2 url :      jdbc:h2:file:C:/study-spring/board/h2data
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate.type: trace